const MOVIES = {
  SEARCH_FETCH_NEW: "SEARCH_FETCH_NEW",
  SEARCH_FETCH_MORE: "SEARCH_FETCH_MORE",
  SEARCH_FETCH_SUCCESS: "SEARCH_FETCH_SUCCESS",
  SEARCH_FETCH_FAIL: "SEARCH_FETCH_FAIL",

  DETAIL_FETCH: "DETAIL_FETCH",
  DETAIL_FETCH_SUCCESS: "DETAIL_FETCH_SUCCESS",
  DETAIL_FETCH_FAIL: "DETAIL_FETCH_FAIL",

  FAVOURITES_LOAD_STORAGE: "FAVOURITES_LOAD_STORAGE",
  FAVOURITES_SAVE_STORAGE: "FAVOURITES_SAVE_STORAGE",

  FAVOURITES_FETCH: "FAVOURITES_FETCH",
  FAVOURITES_FETCH_SUCCESS: "FAVOURITES_FETCH_SUCCESS",
  FAVOURITES_FETCH_FAIL: "FAVOURITES_FETCH_FAIL",
  FAVOURITES_SET: "FAVOURITES_SET",

  FAVOURITES_ADD: "FAVOURITES_ADD",
  FAVOURITES_DELETE: "FAVOURITES_DELETE"
};

export { MOVIES };
